### ISSUE TITLE
Settings KeyError: APP_DIRS must not be set when loaders is defined

### ISSUE THREAD

**Issue by dancaron** [bittner/django-apptemplates#16]
Context: Trying to over ride base_site.html when using django-admin-interface package. I have one file in main/templates/admin, which is base_site.html. And have `{% extends "admin_interface:admin/base_site.html" %}` at top.

**KeyError:**
```
"app_dirs must not be set when loaders is defined."
django.core.exceptions.ImproperlyConfigured: app_dirs must not be set when loaders is defined.
```

settings.py
```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'main/templates/admin'), 
            os.path.join(BASE_DIR, 'main/templates/main'), 
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'loaders':[
                'apptemplates.Loader',
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
```
Removing 'APP_DIRS' causes a TEMPLATE DOES NOT EXIST error. 

Using [django-admin-interface](https://github.com/fabiocaccamo/django-admin-interface) package.

**Comment by dancaron** [comment]
Removing 'APP_DIRS' and adding `django.template.loaders.app_directories.Loader` to 'loaders' seems to have solved the issue.

**Comment by bittner** [comment]
In other words, you don't need `django-apptemplates` at all anymore for your use case? Can you confirm?

**Comment by dancaron** [comment]
After I changed the order of my INSTALLED_APPS, I was able to override django-admin-interface package without django-apptemplates. Appreciate the quick response.

**Comment by pboes** [comment]
@dancaron I'm facing the exact same issue in the exact same context. Do you happen to remember what exactly you did to overwrite django-admin-interface? Thanks

**Comment by dancaron** [comment]
@pboes Sorry, just getting to this message now. Did you resolve your issue?

**Comment by dancaron** [comment]
@pboes Check INSTALLED_APPS, and try moving the order of the entries up or down.

**Comment by pboes** [comment]
Thanks @dancaron, I did solve it in the end. Thanks for getting back to me.
